# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hashfiles.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='hashfiles.proto',
  package='hashfiles',
  syntax='proto3',
  serialized_options=_b('Z\013./hashfiles'),
  serialized_pb=_b('\n\x0fhashfiles.proto\x12\thashfiles\"y\n\x08HashFile\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03url\x18\x02 \x01(\t\x12\x14\n\x0c\x63ontent_hash\x18\x03 \x01(\t\x12)\n\x05words\x18\x06 \x03(\x0b\x32\x1a.hashfiles.WordAndPosition\x12\x11\n\ttext_link\x18\x07 \x01(\t\"M\n\x0fWordAndPosition\x12\x0c\n\x04word\x18\x01 \x01(\t\x12\x16\n\x0estart_position\x18\x02 \x01(\x03\x12\x14\n\x0c\x65nd_position\x18\x03 \x01(\x03\"\'\n\x08WikiData\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\tB\rZ\x0b./hashfilesb\x06proto3')
)




_HASHFILE = _descriptor.Descriptor(
  name='HashFile',
  full_name='hashfiles.HashFile',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='hashfiles.HashFile.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='url', full_name='hashfiles.HashFile.url', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='content_hash', full_name='hashfiles.HashFile.content_hash', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='words', full_name='hashfiles.HashFile.words', index=3,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='text_link', full_name='hashfiles.HashFile.text_link', index=4,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=151,
)


_WORDANDPOSITION = _descriptor.Descriptor(
  name='WordAndPosition',
  full_name='hashfiles.WordAndPosition',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='word', full_name='hashfiles.WordAndPosition.word', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='start_position', full_name='hashfiles.WordAndPosition.start_position', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='end_position', full_name='hashfiles.WordAndPosition.end_position', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=153,
  serialized_end=230,
)


_WIKIDATA = _descriptor.Descriptor(
  name='WikiData',
  full_name='hashfiles.WikiData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='title', full_name='hashfiles.WikiData.title', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='text', full_name='hashfiles.WikiData.text', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=232,
  serialized_end=271,
)

_HASHFILE.fields_by_name['words'].message_type = _WORDANDPOSITION
DESCRIPTOR.message_types_by_name['HashFile'] = _HASHFILE
DESCRIPTOR.message_types_by_name['WordAndPosition'] = _WORDANDPOSITION
DESCRIPTOR.message_types_by_name['WikiData'] = _WIKIDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HashFile = _reflection.GeneratedProtocolMessageType('HashFile', (_message.Message,), dict(
  DESCRIPTOR = _HASHFILE,
  __module__ = 'hashfiles_pb2'
  # @@protoc_insertion_point(class_scope:hashfiles.HashFile)
  ))
_sym_db.RegisterMessage(HashFile)

WordAndPosition = _reflection.GeneratedProtocolMessageType('WordAndPosition', (_message.Message,), dict(
  DESCRIPTOR = _WORDANDPOSITION,
  __module__ = 'hashfiles_pb2'
  # @@protoc_insertion_point(class_scope:hashfiles.WordAndPosition)
  ))
_sym_db.RegisterMessage(WordAndPosition)

WikiData = _reflection.GeneratedProtocolMessageType('WikiData', (_message.Message,), dict(
  DESCRIPTOR = _WIKIDATA,
  __module__ = 'hashfiles_pb2'
  # @@protoc_insertion_point(class_scope:hashfiles.WikiData)
  ))
_sym_db.RegisterMessage(WikiData)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
