# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='messages.proto',
  package='kafka.message',
  syntax='proto3',
  serialized_options=_b('Z\n./messages'),
  serialized_pb=_b('\n\x0emessages.proto\x12\rkafka.message\"Q\n\x0e\x41\x64\x64\x46ileRequest\x12\x11\n\tfile_name\x18\x01 \x01(\t\x12\x0c\n\x04hash\x18\x02 \x01(\t\x12\x0b\n\x03url\x18\x03 \x01(\t\x12\x11\n\tfull_path\x18\x04 \x01(\t\"E\n\tCheckText\x12\x14\n\x0cis_google_on\x18\x01 \x01(\x08\x12\x10\n\x08\x64ocument\x18\x02 \x01(\t\x12\x10\n\x08user_uid\x18\x04 \x01(\t\"Y\n\tCheckFile\x12\x11\n\tfile_name\x18\x01 \x01(\t\x12\x10\n\x08user_uid\x18\x02 \x01(\t\x12\x14\n\x0cis_google_on\x18\x03 \x01(\x08\x12\x11\n\tfull_path\x18\x04 \x01(\t\"\xd4\x01\n\x0f\x43heckTextResult\x12@\n\x0c\x63heck_result\x18\x03 \x01(\x0b\x32*.kafka.message.CheckTextResult.CheckResult\x12\x10\n\x08user_uid\x18\x04 \x01(\t\x1am\n\x0b\x43heckResult\x12\x11\n\tfile_hash\x18\x01 \x01(\t\x12\x11\n\tfile_name\x18\x02 \x01(\t\x12\x1d\n\x15plagiarism_percentage\x18\x03 \x01(\x01\x12\x19\n\x11\x65xtended_data_url\x18\x05 \x01(\tB\x0cZ\n./messagesb\x06proto3')
)




_ADDFILEREQUEST = _descriptor.Descriptor(
  name='AddFileRequest',
  full_name='kafka.message.AddFileRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='file_name', full_name='kafka.message.AddFileRequest.file_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hash', full_name='kafka.message.AddFileRequest.hash', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='url', full_name='kafka.message.AddFileRequest.url', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='full_path', full_name='kafka.message.AddFileRequest.full_path', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=114,
)


_CHECKTEXT = _descriptor.Descriptor(
  name='CheckText',
  full_name='kafka.message.CheckText',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='is_google_on', full_name='kafka.message.CheckText.is_google_on', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='document', full_name='kafka.message.CheckText.document', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user_uid', full_name='kafka.message.CheckText.user_uid', index=2,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=116,
  serialized_end=185,
)


_CHECKFILE = _descriptor.Descriptor(
  name='CheckFile',
  full_name='kafka.message.CheckFile',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='file_name', full_name='kafka.message.CheckFile.file_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user_uid', full_name='kafka.message.CheckFile.user_uid', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_google_on', full_name='kafka.message.CheckFile.is_google_on', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='full_path', full_name='kafka.message.CheckFile.full_path', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=187,
  serialized_end=276,
)


_CHECKTEXTRESULT_CHECKRESULT = _descriptor.Descriptor(
  name='CheckResult',
  full_name='kafka.message.CheckTextResult.CheckResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='file_hash', full_name='kafka.message.CheckTextResult.CheckResult.file_hash', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='file_name', full_name='kafka.message.CheckTextResult.CheckResult.file_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='plagiarism_percentage', full_name='kafka.message.CheckTextResult.CheckResult.plagiarism_percentage', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='extended_data_url', full_name='kafka.message.CheckTextResult.CheckResult.extended_data_url', index=3,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=382,
  serialized_end=491,
)

_CHECKTEXTRESULT = _descriptor.Descriptor(
  name='CheckTextResult',
  full_name='kafka.message.CheckTextResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='check_result', full_name='kafka.message.CheckTextResult.check_result', index=0,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user_uid', full_name='kafka.message.CheckTextResult.user_uid', index=1,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_CHECKTEXTRESULT_CHECKRESULT, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=279,
  serialized_end=491,
)

_CHECKTEXTRESULT_CHECKRESULT.containing_type = _CHECKTEXTRESULT
_CHECKTEXTRESULT.fields_by_name['check_result'].message_type = _CHECKTEXTRESULT_CHECKRESULT
DESCRIPTOR.message_types_by_name['AddFileRequest'] = _ADDFILEREQUEST
DESCRIPTOR.message_types_by_name['CheckText'] = _CHECKTEXT
DESCRIPTOR.message_types_by_name['CheckFile'] = _CHECKFILE
DESCRIPTOR.message_types_by_name['CheckTextResult'] = _CHECKTEXTRESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AddFileRequest = _reflection.GeneratedProtocolMessageType('AddFileRequest', (_message.Message,), dict(
  DESCRIPTOR = _ADDFILEREQUEST,
  __module__ = 'messages_pb2'
  # @@protoc_insertion_point(class_scope:kafka.message.AddFileRequest)
  ))
_sym_db.RegisterMessage(AddFileRequest)

CheckText = _reflection.GeneratedProtocolMessageType('CheckText', (_message.Message,), dict(
  DESCRIPTOR = _CHECKTEXT,
  __module__ = 'messages_pb2'
  # @@protoc_insertion_point(class_scope:kafka.message.CheckText)
  ))
_sym_db.RegisterMessage(CheckText)

CheckFile = _reflection.GeneratedProtocolMessageType('CheckFile', (_message.Message,), dict(
  DESCRIPTOR = _CHECKFILE,
  __module__ = 'messages_pb2'
  # @@protoc_insertion_point(class_scope:kafka.message.CheckFile)
  ))
_sym_db.RegisterMessage(CheckFile)

CheckTextResult = _reflection.GeneratedProtocolMessageType('CheckTextResult', (_message.Message,), dict(

  CheckResult = _reflection.GeneratedProtocolMessageType('CheckResult', (_message.Message,), dict(
    DESCRIPTOR = _CHECKTEXTRESULT_CHECKRESULT,
    __module__ = 'messages_pb2'
    # @@protoc_insertion_point(class_scope:kafka.message.CheckTextResult.CheckResult)
    ))
  ,
  DESCRIPTOR = _CHECKTEXTRESULT,
  __module__ = 'messages_pb2'
  # @@protoc_insertion_point(class_scope:kafka.message.CheckTextResult)
  ))
_sym_db.RegisterMessage(CheckTextResult)
_sym_db.RegisterMessage(CheckTextResult.CheckResult)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
