"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class AddFileRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    FILE_NAME_FIELD_NUMBER: builtins.int
    HASH_FIELD_NUMBER: builtins.int
    URL_FIELD_NUMBER: builtins.int
    FULL_PATH_FIELD_NUMBER: builtins.int
    file_name: typing.Text
    hash: typing.Text
    """hash of the file"""

    url: typing.Text
    full_path: typing.Text
    """full_path is the full path of the file on the local filesystem"""

    def __init__(self,
        *,
        file_name: typing.Text = ...,
        hash: typing.Text = ...,
        url: typing.Optional[typing.Text] = ...,
        full_path: typing.Text = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["_url",b"_url","url",b"url"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["_url",b"_url","file_name",b"file_name","full_path",b"full_path","hash",b"hash","url",b"url"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_url",b"_url"]) -> typing.Optional[typing_extensions.Literal["url"]]: ...
global___AddFileRequest = AddFileRequest

class CheckText(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    IS_GOOGLE_ON_FIELD_NUMBER: builtins.int
    DOCUMENT_FIELD_NUMBER: builtins.int
    USER_UID_FIELD_NUMBER: builtins.int
    is_google_on: builtins.bool
    document: typing.Text
    user_uid: typing.Text
    def __init__(self,
        *,
        is_google_on: builtins.bool = ...,
        document: typing.Text = ...,
        user_uid: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["document",b"document","is_google_on",b"is_google_on","user_uid",b"user_uid"]) -> None: ...
global___CheckText = CheckText

class CheckTextResult(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    class CheckResult(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor
        FILE_HASH_FIELD_NUMBER: builtins.int
        FILE_NAME_FIELD_NUMBER: builtins.int
        PLAGIARISM_PERCENTAGE_FIELD_NUMBER: builtins.int
        PLAGIARISM_RESULT_FIELD_NUMBER: builtins.int
        file_hash: typing.Text
        file_name: typing.Text
        plagiarism_percentage: builtins.float
        @property
        def plagiarism_result(self) -> global___CheckTextResult.PlagiarismResult: ...
        def __init__(self,
            *,
            file_hash: typing.Text = ...,
            file_name: typing.Text = ...,
            plagiarism_percentage: builtins.float = ...,
            plagiarism_result: typing.Optional[global___CheckTextResult.PlagiarismResult] = ...,
            ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["plagiarism_result",b"plagiarism_result"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["file_hash",b"file_hash","file_name",b"file_name","plagiarism_percentage",b"plagiarism_percentage","plagiarism_result",b"plagiarism_result"]) -> None: ...

    class PlagiarismResult(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor
        SIMILAR_FILES_FIELD_NUMBER: builtins.int
        SEQUENCES_FIELD_NUMBER: builtins.int
        URLS_FIELD_NUMBER: builtins.int
        TEXT_FIELD_NUMBER: builtins.int
        SYMBOL_REPLACEMENTS_FIELD_NUMBER: builtins.int
        @property
        def similar_files(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___CheckTextResult.SimilarFile]: ...
        @property
        def sequences(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___CheckTextResult.Sequence]: ...
        @property
        def urls(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[typing.Text]: ...
        text: typing.Text
        @property
        def symbol_replacements(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
        def __init__(self,
            *,
            similar_files: typing.Optional[typing.Iterable[global___CheckTextResult.SimilarFile]] = ...,
            sequences: typing.Optional[typing.Iterable[global___CheckTextResult.Sequence]] = ...,
            urls: typing.Optional[typing.Iterable[typing.Text]] = ...,
            text: typing.Text = ...,
            symbol_replacements: typing.Optional[typing.Iterable[builtins.int]] = ...,
            ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["sequences",b"sequences","similar_files",b"similar_files","symbol_replacements",b"symbol_replacements","text",b"text","urls",b"urls"]) -> None: ...

    class SimilarFile(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor
        FILE_NAME_FIELD_NUMBER: builtins.int
        URL_FIELD_NUMBER: builtins.int
        file_name: typing.Text
        url: typing.Text
        def __init__(self,
            *,
            file_name: typing.Text = ...,
            url: typing.Optional[typing.Text] = ...,
            ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["_url",b"_url","url",b"url"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["_url",b"_url","file_name",b"file_name","url",b"url"]) -> None: ...
        def WhichOneof(self, oneof_group: typing_extensions.Literal["_url",b"_url"]) -> typing.Optional[typing_extensions.Literal["url"]]: ...

    class Sequence(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor
        START_FIELD_NUMBER: builtins.int
        END_FIELD_NUMBER: builtins.int
        start: builtins.int
        end: builtins.int
        def __init__(self,
            *,
            start: builtins.int = ...,
            end: builtins.int = ...,
            ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["end",b"end","start",b"start"]) -> None: ...

    CHECK_RESULT_FIELD_NUMBER: builtins.int
    USER_UID_FIELD_NUMBER: builtins.int
    @property
    def check_result(self) -> global___CheckTextResult.CheckResult: ...
    user_uid: typing.Text
    def __init__(self,
        *,
        check_result: typing.Optional[global___CheckTextResult.CheckResult] = ...,
        user_uid: typing.Text = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["check_result",b"check_result"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["check_result",b"check_result","user_uid",b"user_uid"]) -> None: ...
global___CheckTextResult = CheckTextResult
