// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.22.0
// source: hashfiles.proto

package hashfiles

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HashFile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string             `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Url         string             `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	ContentHash string             `protobuf:"bytes,3,opt,name=content_hash,json=contentHash,proto3" json:"content_hash,omitempty"`
	Words       []*WordAndPosition `protobuf:"bytes,6,rep,name=words,proto3" json:"words,omitempty"`
	TextLink    string             `protobuf:"bytes,7,opt,name=text_link,json=textLink,proto3" json:"text_link,omitempty"`
}

func (x *HashFile) Reset() {
	*x = HashFile{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hashfiles_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HashFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HashFile) ProtoMessage() {}

func (x *HashFile) ProtoReflect() protoreflect.Message {
	mi := &file_hashfiles_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HashFile.ProtoReflect.Descriptor instead.
func (*HashFile) Descriptor() ([]byte, []int) {
	return file_hashfiles_proto_rawDescGZIP(), []int{0}
}

func (x *HashFile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HashFile) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *HashFile) GetContentHash() string {
	if x != nil {
		return x.ContentHash
	}
	return ""
}

func (x *HashFile) GetWords() []*WordAndPosition {
	if x != nil {
		return x.Words
	}
	return nil
}

func (x *HashFile) GetTextLink() string {
	if x != nil {
		return x.TextLink
	}
	return ""
}

type WordAndPosition struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Word          string `protobuf:"bytes,1,opt,name=word,proto3" json:"word,omitempty"`
	StartPosition int64  `protobuf:"varint,2,opt,name=start_position,json=startPosition,proto3" json:"start_position,omitempty"`
	EndPosition   int64  `protobuf:"varint,3,opt,name=end_position,json=endPosition,proto3" json:"end_position,omitempty"`
}

func (x *WordAndPosition) Reset() {
	*x = WordAndPosition{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hashfiles_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WordAndPosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WordAndPosition) ProtoMessage() {}

func (x *WordAndPosition) ProtoReflect() protoreflect.Message {
	mi := &file_hashfiles_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WordAndPosition.ProtoReflect.Descriptor instead.
func (*WordAndPosition) Descriptor() ([]byte, []int) {
	return file_hashfiles_proto_rawDescGZIP(), []int{1}
}

func (x *WordAndPosition) GetWord() string {
	if x != nil {
		return x.Word
	}
	return ""
}

func (x *WordAndPosition) GetStartPosition() int64 {
	if x != nil {
		return x.StartPosition
	}
	return 0
}

func (x *WordAndPosition) GetEndPosition() int64 {
	if x != nil {
		return x.EndPosition
	}
	return 0
}

var File_hashfiles_proto protoreflect.FileDescriptor

var file_hashfiles_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x68, 0x61, 0x73, 0x68, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x09, 0x68, 0x61, 0x73, 0x68, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x22, 0xa2, 0x01, 0x0a,
	0x08, 0x48, 0x61, 0x73, 0x68, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a,
	0x03, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12,
	0x21, 0x0a, 0x0c, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x48, 0x61,
	0x73, 0x68, 0x12, 0x30, 0x0a, 0x05, 0x77, 0x6f, 0x72, 0x64, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x68, 0x61, 0x73, 0x68, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x2e, 0x57, 0x6f,
	0x72, 0x64, 0x41, 0x6e, 0x64, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x05, 0x77,
	0x6f, 0x72, 0x64, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x65, 0x78, 0x74, 0x5f, 0x6c, 0x69, 0x6e,
	0x6b, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x65, 0x78, 0x74, 0x4c, 0x69, 0x6e,
	0x6b, 0x22, 0x6f, 0x0a, 0x0f, 0x57, 0x6f, 0x72, 0x64, 0x41, 0x6e, 0x64, 0x50, 0x6f, 0x73, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x25, 0x0a, 0x0e, 0x73, 0x74, 0x61, 0x72,
	0x74, 0x5f, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x0d, 0x73, 0x74, 0x61, 0x72, 0x74, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x21, 0x0a, 0x0c, 0x65, 0x6e, 0x64, 0x5f, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x65, 0x6e, 0x64, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x42, 0x0d, 0x5a, 0x0b, 0x2e, 0x2f, 0x68, 0x61, 0x73, 0x68, 0x66, 0x69, 0x6c, 0x65,
	0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_hashfiles_proto_rawDescOnce sync.Once
	file_hashfiles_proto_rawDescData = file_hashfiles_proto_rawDesc
)

func file_hashfiles_proto_rawDescGZIP() []byte {
	file_hashfiles_proto_rawDescOnce.Do(func() {
		file_hashfiles_proto_rawDescData = protoimpl.X.CompressGZIP(file_hashfiles_proto_rawDescData)
	})
	return file_hashfiles_proto_rawDescData
}

var file_hashfiles_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_hashfiles_proto_goTypes = []interface{}{
	(*HashFile)(nil),        // 0: hashfiles.HashFile
	(*WordAndPosition)(nil), // 1: hashfiles.WordAndPosition
}
var file_hashfiles_proto_depIdxs = []int32{
	1, // 0: hashfiles.HashFile.words:type_name -> hashfiles.WordAndPosition
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_hashfiles_proto_init() }
func file_hashfiles_proto_init() {
	if File_hashfiles_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_hashfiles_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HashFile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hashfiles_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WordAndPosition); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_hashfiles_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_hashfiles_proto_goTypes,
		DependencyIndexes: file_hashfiles_proto_depIdxs,
		MessageInfos:      file_hashfiles_proto_msgTypes,
	}.Build()
	File_hashfiles_proto = out.File
	file_hashfiles_proto_rawDesc = nil
	file_hashfiles_proto_goTypes = nil
	file_hashfiles_proto_depIdxs = nil
}
